Repository ETombuyses/agora, pull requests merged in 2020-07, with the labels that each got.

#45 New content for january
  src/routes/Stats.jsx
Labels: to-review

#55 feat(Dashboard): Add images
  .gitignore
  src/assets/images/persona/aymeric-persona.svg
  src/assets/images/persona/bastien-persona.svg
  src/assets/images/persona/default-persona.svg
  src/assets/images/persona/gabriel-persona.svg
  src/assets/images/persona/helene-persona.svg
  src/assets/images/profile/aymeric-profile.svg
  src/assets/images/profile/bastien-profile.svg
  src/assets/images/profile/default-profile.svg
  src/assets/images/profile/gabriel-profile.svg
  src/assets/images/profile/helene-profile.svg
  src/components/atoms/task/Icon.jsx
  src/components/atoms/task/Title.jsx
  src/components/molecules/Task.jsx
  src/components/molecules/user/WelcomeBanner.jsx
  src/components/organisms/UserPanel.jsx
  src/tools/pickPersonaSvg.js
  src/tools/pickProfileSvg.js
Labels: feature

#59 fix(Avatar): Change behavior
  src/components/molecules/user/WelcomeBanner.jsx
  src/components/organisms/UserPanel.jsx
  src/tools/pickPersonaSvg.js
  src/tools/pickProfileSvg.js
Labels: bug

#61 fix(Avatar): Change to be components
  src/components/atoms/chart/Radar.jsx
  src/components/atoms/layout/SvgPersona.jsx
  src/components/atoms/layout/SvgProfile.jsx
  src/components/molecules/user/WelcomeBanner.jsx
  src/components/organisms/UserPanel.jsx
  src/tools/pickPersonaSvg.js
  src/tools/pickProfileSvg.js
Labels: bug

#64 fix(Avatar): Change implementation
  src/components/atoms/layout/SvgPersona.jsx
  src/components/atoms/layout/SvgProfile.jsx
  src/tools/getRightComponent.js
Labels: bug
